-- FIX COMPLETO SUPABASE — Via Log
-- Rode este arquivo no SQL Editor para corrigir base legado + base v2.
-- Ele é seguro para rodar mais de uma vez.

create extension if not exists pgcrypto;

-- =========================================================
-- 1) LEGADO: usado pelo painel de estadias atual
-- =========================================================
create table if not exists public.ldc_estadias (
  id bigint generated by default as identity primary key,
  local_id text not null unique,
  tipo text not null,
  filial text not null default 'principal',
  placa text,
  status text,
  prioridade text default 'Normal',
  dados jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists idx_ldc_estadias_tipo on public.ldc_estadias(tipo);
create index if not exists idx_ldc_estadias_filial on public.ldc_estadias(filial);
create index if not exists idx_ldc_estadias_local_id on public.ldc_estadias(local_id);
create index if not exists idx_ldc_estadias_updated_at on public.ldc_estadias(updated_at desc);

create table if not exists public.ldc_usuarios (
  usuario text primary key,
  senha text not null,
  nome text not null,
  cargo text not null default 'Operador',
  avatar text,
  foto text,
  filial text not null default 'principal',
  updated_at timestamptz not null default now()
);

-- =========================================================
-- 2) V2: captação e motoristas normalizados
-- =========================================================
create table if not exists public.vl_filiais (
  id text primary key,
  nome text not null,
  cidade text,
  estado text,
  ativa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vl_profiles (
  usuario text primary key,
  auth_uid uuid unique,
  nome text not null,
  cargo text not null default 'Operador' check (cargo in ('Admin','Operador','Visualizador')),
  filial_id text references public.vl_filiais(id),
  avatar text,
  foto text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vl_motoristas (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  telefone text,
  telefone_limpo text unique,
  cidade text,
  observacao text,
  criado_por text references public.vl_profiles(usuario),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vl_captacoes (
  id uuid primary key default gen_random_uuid(),
  local_id text unique,
  motorista_id uuid references public.vl_motoristas(id) on delete set null,
  captador_usuario text references public.vl_profiles(usuario),
  filial_id text references public.vl_filiais(id),
  operacao text not null default 'Farelo',
  status text not null default 'contatado' check (status in ('contatado','ordem','carregou')),
  observacao text,
  quantidade_cargas integer not null default 1 check (quantidade_cargas > 0),
  data_captacao timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_vl_captacoes_filial on public.vl_captacoes(filial_id);
create index if not exists idx_vl_captacoes_captador on public.vl_captacoes(captador_usuario);
create index if not exists idx_vl_captacoes_status on public.vl_captacoes(status);
create index if not exists idx_vl_captacoes_operacao on public.vl_captacoes(operacao);

create table if not exists public.vl_captacao_eventos (
  id uuid primary key default gen_random_uuid(),
  captacao_id uuid references public.vl_captacoes(id) on delete cascade,
  status_anterior text,
  status_novo text not null,
  usuario text references public.vl_profiles(usuario),
  observacao text,
  created_at timestamptz not null default now()
);

create table if not exists public.vl_motorista_carregamentos (
  id uuid primary key default gen_random_uuid(),
  motorista_id uuid references public.vl_motoristas(id) on delete cascade,
  captacao_id uuid references public.vl_captacoes(id) on delete cascade,
  filial_id text references public.vl_filiais(id),
  operacao text,
  captador_usuario text references public.vl_profiles(usuario),
  observacao text,
  carregou_em timestamptz not null default now(),
  unique(captacao_id)
);

create index if not exists idx_vl_carregamentos_motorista on public.vl_motorista_carregamentos(motorista_id);
create index if not exists idx_vl_carregamentos_filial on public.vl_motorista_carregamentos(filial_id);
create index if not exists idx_vl_carregamentos_captador on public.vl_motorista_carregamentos(captador_usuario);

create table if not exists public.vl_estadias (
  id uuid primary key default gen_random_uuid(),
  local_id text unique,
  filial_id text references public.vl_filiais(id),
  chamado text,
  motorista text,
  transportadora text,
  placa text,
  peso numeric,
  chegada timestamptz,
  saida timestamptz,
  horas numeric,
  valor numeric,
  pago_por text,
  prioridade text default 'Normal',
  status text default 'Aberto',
  lancado_por text references public.vl_profiles(usuario),
  feito_por text references public.vl_profiles(usuario),
  finalizado_por text references public.vl_profiles(usuario),
  dados jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vl_estadias_a_lancar (
  id uuid primary key default gen_random_uuid(),
  local_id text unique,
  filial_id text references public.vl_filiais(id),
  placa text not null,
  transportadora text,
  prioridade text default 'Normal',
  observacao text,
  status text default 'A lançar',
  criado_por text references public.vl_profiles(usuario),
  dados jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vl_anexos (
  id uuid primary key default gen_random_uuid(),
  origem_tipo text not null check (origem_tipo in ('estadia','a_lancar','captacao')),
  origem_local_id text not null,
  nome text,
  tipo text,
  tamanho bigint,
  url text not null,
  cloud boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.vl_historico_eventos (
  id uuid primary key default gen_random_uuid(),
  origem_tipo text not null,
  origem_local_id text,
  usuario text references public.vl_profiles(usuario),
  acao text not null,
  detalhes text,
  dados jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- =========================================================
-- 3) Storage bucket para anexos
-- =========================================================
insert into storage.buckets (id, name, public)
values ('ldc-anexos', 'ldc-anexos', true)
on conflict (id) do update set public = true;

-- =========================================================
-- 4) Triggers
-- =========================================================
create or replace function public.vl_touch_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_vl_filiais_touch on public.vl_filiais;
create trigger trg_vl_filiais_touch before update on public.vl_filiais for each row execute function public.vl_touch_updated_at();

drop trigger if exists trg_vl_profiles_touch on public.vl_profiles;
create trigger trg_vl_profiles_touch before update on public.vl_profiles for each row execute function public.vl_touch_updated_at();

drop trigger if exists trg_vl_motoristas_touch on public.vl_motoristas;
create trigger trg_vl_motoristas_touch before update on public.vl_motoristas for each row execute function public.vl_touch_updated_at();

drop trigger if exists trg_vl_captacoes_touch on public.vl_captacoes;
create trigger trg_vl_captacoes_touch before update on public.vl_captacoes for each row execute function public.vl_touch_updated_at();

create or replace function public.vl_registrar_carregamento_captacao()
returns trigger as $$
begin
  if new.status = 'carregou' then
    insert into public.vl_motorista_carregamentos (
      motorista_id, captacao_id, filial_id, operacao, captador_usuario, observacao, carregou_em
    ) values (
      new.motorista_id, new.id, new.filial_id, new.operacao, new.captador_usuario, new.observacao, now()
    )
    on conflict (captacao_id) do update set
      motorista_id = excluded.motorista_id,
      filial_id = excluded.filial_id,
      operacao = excluded.operacao,
      captador_usuario = excluded.captador_usuario,
      observacao = excluded.observacao;
  end if;

  if tg_op = 'UPDATE' and old.status is distinct from new.status then
    insert into public.vl_captacao_eventos (captacao_id, status_anterior, status_novo, usuario, observacao)
    values (new.id, old.status, new.status, new.captador_usuario, new.observacao);
  elsif tg_op = 'INSERT' then
    insert into public.vl_captacao_eventos (captacao_id, status_anterior, status_novo, usuario, observacao)
    values (new.id, null, new.status, new.captador_usuario, new.observacao);
  end if;

  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_vl_captacoes_carregamento on public.vl_captacoes;
create trigger trg_vl_captacoes_carregamento after insert or update on public.vl_captacoes
for each row execute function public.vl_registrar_carregamento_captacao();

-- =========================================================
-- 5) Views
-- =========================================================
create or replace view public.vw_motoristas_que_carregam as
select
  m.id,
  m.nome,
  m.telefone,
  m.telefone_limpo,
  count(mc.id)::integer as carregamentos,
  array_remove(array_agg(distinct mc.operacao), null) as operacoes,
  array_remove(array_agg(distinct mc.filial_id), null) as filiais,
  array_remove(array_agg(distinct mc.captador_usuario), null) as captadores,
  max(mc.carregou_em) as ultimo_carregamento,
  max(mc.observacao) as ultima_observacao
from public.vl_motoristas m
join public.vl_motorista_carregamentos mc on mc.motorista_id = m.id
group by m.id, m.nome, m.telefone, m.telefone_limpo;

-- =========================================================
-- 6) RLS permissivo para o app atual
-- =========================================================
alter table public.ldc_estadias enable row level security;
alter table public.ldc_usuarios enable row level security;
alter table public.vl_filiais enable row level security;
alter table public.vl_profiles enable row level security;
alter table public.vl_motoristas enable row level security;
alter table public.vl_captacoes enable row level security;
alter table public.vl_captacao_eventos enable row level security;
alter table public.vl_motorista_carregamentos enable row level security;
alter table public.vl_estadias enable row level security;
alter table public.vl_estadias_a_lancar enable row level security;
alter table public.vl_anexos enable row level security;
alter table public.vl_historico_eventos enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array[
    'ldc_estadias','ldc_usuarios','vl_filiais','vl_profiles','vl_motoristas','vl_captacoes','vl_captacao_eventos',
    'vl_motorista_carregamentos','vl_estadias','vl_estadias_a_lancar','vl_anexos','vl_historico_eventos'
  ] loop
    execute format('drop policy if exists "dev anon all" on public.%I', t);
    execute format('create policy "dev anon all" on public.%I for all to anon, authenticated using (true) with check (true)', t);
  end loop;
end $$;

-- Storage policies
create policy if not exists "public read ldc anexos" on storage.objects
for select to anon, authenticated using (bucket_id = 'ldc-anexos');

create policy if not exists "public insert ldc anexos" on storage.objects
for insert to anon, authenticated with check (bucket_id = 'ldc-anexos');

create policy if not exists "public update ldc anexos" on storage.objects
for update to anon, authenticated using (bucket_id = 'ldc-anexos') with check (bucket_id = 'ldc-anexos');

create policy if not exists "public delete ldc anexos" on storage.objects
for delete to anon, authenticated using (bucket_id = 'ldc-anexos');

-- =========================================================
-- 7) Seeds mínimos
-- =========================================================
insert into public.vl_filiais (id, nome, cidade, estado)
values
  ('jatai-go', 'Jataí - GO', 'Jataí', 'GO'),
  ('mineiros-go', 'Mineiros - GO', 'Mineiros', 'GO'),
  ('rondonopolis-mt', 'Rondonópolis - MT', 'Rondonópolis', 'MT')
on conflict (id) do update set nome = excluded.nome, cidade = excluded.cidade, estado = excluded.estado;
